### ISSUE TITLE
Scrape without Apple hardware

### ISSUE THREAD

**Issue by mrx23dot** [comp-journalism/apple-news-scraper#3]
Is it possible to scrape it without any Apple hardware?
Do you have an Apply API endpoint?

**Comment by mrx23dot** [comment]
wiki "The Apple News app works by pulling in news stories from the web through various syndication feeds (Atom and RSS)[13] or from news publishing partners through the JSON descriptive Apple News Format."

**Comment by jackbandy** [comment]
Great question! Last time I tried, this was not possible as Apple News was using SSL pinning on their endpoints. One might be able to access endpoints from individual publishers, but it wouldn't be possible to see how their stories were featured in the app.

**Comment by mrx23dot** [comment]
Bypassing ssl pinning seems way too much effort :(
https://www.cyberlands.io/sslpinningbypassios
